name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Generate and Push Snake
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v3

      # Generate SVG snake
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        id: snake-svg
        with:
          github_user_name: akshsrin
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Generate GIF snake (optional)
      - name: Generate Snake GIF
        uses: Platane/snk/gif@v3
        id: snake-gif
        with:
          github_user_name: akshsrin
          outputs: |
            dist/github-contribution-grid-snake.gif

      # Push SVG & GIF to 'output' branch
      - name: Push Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          personal_token: ${{ secrets.GH_PAT }}
